-- Future authenticated sync. MVP stores private history in browser; do not expose these tables through public policies.
create extension if not exists pgcrypto;
create table if not exists public.languages (id text primary key, name text not null);
insert into public.languages (id, name) values ('en','English'),('ja','Japanese') on conflict do nothing;
create table if not exists public.training_modes (id text primary key, name text not null);
insert into public.training_modes (id,name) values ('ielts','IELTS Speaking'),('daily','Daily Conversation'),('scenario','Scenario Practice'),('topic','Topic Practice'),('free-talk','Free Talk'),('toefl','TOEFL Speaking'),('interview','Interview Practice'),('weakness','Weakness Practice') on conflict do nothing;
create table if not exists public.users (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table if not exists public.user_language_profiles (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, language text not null references public.languages(id), level text, exam_goal text, level_reference text, unique(user_id,language));
create table if not exists public.practice_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, language text not null references public.languages(id), training_type text not null references public.training_modes(id), exam_type text, level text, topic text, status text not null default 'idle', created_at timestamptz not null default now(), ended_at timestamptz);
create table if not exists public.questions (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.practice_sessions(id) on delete cascade, content text not null, position integer not null, created_at timestamptz not null default now());
create table if not exists public.answers (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.practice_sessions(id) on delete cascade, question_id uuid references public.questions(id), attempt_number integer not null default 1, duration_seconds integer not null default 0, created_at timestamptz not null default now());
create table if not exists public.audio_records (id uuid primary key default gen_random_uuid(), answer_id uuid not null references public.answers(id) on delete cascade, storage_path text not null, mime_type text, created_at timestamptz not null default now());
create table if not exists public.transcripts (id uuid primary key default gen_random_uuid(), answer_id uuid not null references public.answers(id) on delete cascade, language text not null references public.languages(id), content text not null, created_at timestamptz not null default now());
create table if not exists public.evaluations (id uuid primary key default gen_random_uuid(), session_id uuid not null references public.practice_sessions(id) on delete cascade, model text not null, summary text, created_at timestamptz not null default now());
create table if not exists public.scores (id uuid primary key default gen_random_uuid(), evaluation_id uuid not null references public.evaluations(id) on delete cascade, rubric_key text not null, value numeric(4,1) not null, note text);
create table if not exists public.feedback (id uuid primary key default gen_random_uuid(), evaluation_id uuid not null references public.evaluations(id) on delete cascade, kind text not null, content text not null);
create table if not exists public.attempts (id uuid primary key default gen_random_uuid(), answer_id uuid not null references public.answers(id) on delete cascade, prior_answer_id uuid references public.answers(id), comparison jsonb default '{}'::jsonb);
create table if not exists public.weaknesses (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, language text not null references public.languages(id), category text not null, evidence text, observed_at timestamptz not null default now());
do $$ declare table_name text; begin foreach table_name in array array['users','user_language_profiles','practice_sessions','questions','answers','audio_records','transcripts','evaluations','scores','feedback','attempts','weaknesses'] loop execute format('alter table public.%I enable row level security',table_name); end loop; end $$;
-- Add explicit owner policies only when authenticated sync endpoints are implemented.
