export type LanguageId = 'en' | 'ja';
export type ModeId = 'ielts' | 'daily' | 'scenario' | 'topic' | 'free-talk' | 'toefl' | 'interview' | 'weakness';
export type SessionStatus = 'idle' | 'ai-speaking' | 'listening' | 'recording' | 'processing' | 'thinking' | 'finished';
import type { AudioMetrics, TranscriptResult } from '@/lib/speech/types';
export type Turn = { id: string; question: string; transcript: string; audioId?: string; createdAt: string; attempt: number; durationSeconds: number; aiResponse?: string; examPart?: 1 | 2 | 3; audioMetrics?: AudioMetrics; transcriptResult?: TranscriptResult };
export type Score = { key: string; label: string; value: number; note: string };
export type Evaluation = { summary: string; scores: Score[]; strengths: string[]; improvements: string[]; weaknesses: string[]; model: 'ai' | 'demo' };
export type Session = { id: string; language: LanguageId; mode: ModeId; level: string; topic: string; status: SessionStatus; question: string; turns: Turn[]; startedAt: string; endedAt?: string; evaluation?: Evaluation; examType?: string | null; examSetId?: string };
export type LanguageConfig = { id: LanguageId; name: string; nativeName: string; flag: string; accent: string; description: string; levels: string[]; modes: ModeId[]; topics: Record<string, string[]>; fallbackQuestions: Record<string, string[]>; rubric: { key: string; label: string; guide: string }[]; weaknesses: string[]; conversationPrompt: string; evaluationPrompt: string; speechLocale: string };
export type ModeConfig = { id: ModeId; title: string; short: string; role: string; icon: string; description: string; enabled: boolean; prompt: string; maxTurns: number; rubric?: { key: string; label: string; guide: string }[] };
