'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, AudioLines, BarChart3, BookOpen, Check, ChevronRight, CircleHelp, Clock3, Headphones, Home, Languages, Mic, Moon, MoreHorizontal, Pause, Play, RotateCcw, Settings2, Sparkles, Square, Sun, Target, UserRound, Volume2, WandSparkles, X } from 'lucide-react';
import { languages } from '@/languages';
import { modes } from '@/training/config';
import { createSession, speakingReducer } from '@/core/speaking/engine';
import { getSessions, getStats, saveSession } from '@/core/session/storage';
import { AudioRecorder } from '@/core/audio/recorder';
import { getAudio, saveAudio } from '@/core/audio/store';
import { demoEvaluation, demoQuestion } from '@/lib/ai/demo';
import type { LanguageId, ModeId, Session, Turn } from '@/types/speaking';

type Page = 'home' | 'practice' | 'setup' | 'speaking' | 'result' | 'progress' | 'profile';
type UiLanguage = 'zh-CN' | 'en' | 'zh-HK' | 'ja';
type Theme = 'light' | 'dark';
type TextProvider = 'openai' | 'deepseek' | 'glm';
const interfaceLanguages: { id: UiLanguage; label: string }[] = [
  { id: 'zh-CN', label: '简体中文' }, { id: 'en', label: 'English' }, { id: 'zh-HK', label: '繁體中文（香港）' }, { id: 'ja', label: '日本語' },
];
const uiCopy: Record<UiLanguage, Record<string, string>> = {
  'zh-CN': { studio: '口语工作室', settings: '界面设置', interfaceLanguage: '界面语言', appearance: '显示模式', light: '浅色模式', dark: '深色模式', close: '关闭', daily: '你的每日口语空间', voice: '找到你的声音。', further: '继续前行。', intro: '真实对话。贴心反馈。看得见的进步。', begin: '开始练习', choose: '选择学习语言', journey: '你的历程', sessions: '次练习', minutes: '分钟口语', streak: '连续练习*', home: '首页', practice: '练习', progress: '进度', profile: '我的', settingsHint: '设置界面语言和显示模式。' },
  en: { studio: 'SPEAKING STUDIO', settings: 'Interface settings', interfaceLanguage: 'Interface language', appearance: 'Appearance', light: 'Light mode', dark: 'Dark mode', close: 'Close', daily: 'YOUR DAILY SPEAKING SPACE', voice: 'Find your voice.', further: 'Go further.', intro: 'Real conversations. Thoughtful feedback. Progress you can feel.', begin: 'LET’S BEGIN', choose: 'Choose a language', journey: 'YOUR JOURNEY', sessions: 'sessions', minutes: 'minutes spoken', streak: 'streak*', home: 'Home', practice: 'Practice', progress: 'Progress', profile: 'Profile', settingsHint: 'Set interface language and appearance.' },
  'zh-HK': { studio: '口語工作室', settings: '介面設定', interfaceLanguage: '介面語言', appearance: '顯示模式', light: '淺色模式', dark: '深色模式', close: '關閉', daily: '你的每日口語空間', voice: '找到你的聲音。', further: '繼續前行。', intro: '真實對話。貼心回饋。看得見的進步。', begin: '開始練習', choose: '選擇學習語言', journey: '你的歷程', sessions: '次練習', minutes: '分鐘口語', streak: '連續練習*', home: '首頁', practice: '練習', progress: '進度', profile: '我的', settingsHint: '設定介面語言和顯示模式。' },
  ja: { studio: 'スピーキングスタジオ', settings: '表示設定', interfaceLanguage: '表示言語', appearance: '表示モード', light: 'ライトモード', dark: 'ダークモード', close: '閉じる', daily: '毎日のスピーキング空間', voice: '声を見つけよう。', further: 'もっと先へ。', intro: 'リアルな会話。丁寧なフィードバック。実感できる進歩。', begin: '始めましょう', choose: '学習言語を選ぶ', journey: 'あなたの記録', sessions: 'セッション', minutes: '話した分数', streak: '連続記録*', home: 'ホーム', practice: '練習', progress: '進捗', profile: 'プロフィール', settingsHint: '表示言語とテーマを設定。' },
};
const iconMap = { ielts: BookOpen, daily: AudioLines, scenario: Target, topic: Sparkles, 'free-talk': Mic, toefl: BookOpen, interview: UserRound, weakness: Target };
const formatTime = (seconds: number) => `${Math.floor(seconds / 60).toString().padStart(2, '0')}:${(seconds % 60).toString().padStart(2, '0')}`;

export function OralApp() {
  const [page, setPage] = useState<Page>('home'); const [language, setLanguage] = useState<LanguageId>('en'); const [mode, setMode] = useState<ModeId>('daily'); const [level, setLevel] = useState('Intermediate'); const [topic, setTopic] = useState('Everyday life');
  const [session, setSession] = useState<Session | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [recording, setRecording] = useState(false); const [paused, setPaused] = useState(false); const [seconds, setSeconds] = useState(0);
  const [audio, setAudio] = useState<Blob | null>(null); const [audioUrl, setAudioUrl] = useState(''); const [transcript, setTranscript] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const [tab, setTab] = useState<'all' | LanguageId>('all');
  const [uiLanguage, setUiLanguage] = useState<UiLanguage>('en'); const [theme, setTheme] = useState<Theme>('light'); const [settingsOpen, setSettingsOpen] = useState(false); const [textProvider, setTextProvider] = useState<TextProvider>('openai'); const [accessCode, setAccessCode] = useState('');
  const recorder = useRef<AudioRecorder | null>(null); const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  useEffect(() => { setSessions(getSessions()); }, []);
  useEffect(() => { const savedLanguage = localStorage.getItem('oral-ui-language') as UiLanguage | null; const savedTheme = localStorage.getItem('oral-theme') as Theme | null; if (savedLanguage && uiCopy[savedLanguage]) setUiLanguage(savedLanguage); if (savedTheme === 'light' || savedTheme === 'dark') setTheme(savedTheme); }, []);
  useEffect(() => { setAccessCode(sessionStorage.getItem('oral-beta-access-code') || ''); }, []);
  useEffect(() => { document.documentElement.lang = uiLanguage; document.documentElement.dataset.theme = theme; localStorage.setItem('oral-ui-language', uiLanguage); localStorage.setItem('oral-theme', theme); }, [uiLanguage, theme]);
  useEffect(() => { if (accessCode) sessionStorage.setItem('oral-beta-access-code', accessCode); else sessionStorage.removeItem('oral-beta-access-code'); }, [accessCode]);
  useEffect(() => { if (session) { saveSession(session); setSessions(getSessions()); } }, [session]);
  useEffect(() => { return () => { if (timer.current) clearInterval(timer.current); recorder.current?.dispose(); }; }, []);
  useEffect(() => { if (page !== 'speaking' && recorder.current?.state !== 'inactive') { recorder.current?.dispose(); if (timer.current) clearInterval(timer.current); setRecording(false); setPaused(false); } }, [page]);
  useEffect(() => { if (!audio) { setAudioUrl(''); return; } const url = URL.createObjectURL(audio); setAudioUrl(url); return () => URL.revokeObjectURL(url); }, [audio]);
  const config = languages[language]; const activeMode = modes[mode]; const stats = getStats(sessions); const currentStats = getStats(sessions, tab === 'all' ? undefined : tab); const text = uiCopy[uiLanguage];
  function chooseLanguage(id: LanguageId) { setLanguage(id); setLevel(id === 'ja' ? 'Beginner' : 'Intermediate'); setMode('daily'); setTopic(languages[id].topics.daily[0]); setPage('practice'); }
  function chooseMode(id: ModeId) { if (!modes[id].enabled) return; setMode(id); setTopic(config.topics[id]?.[0] || config.topics.daily[0]); setPage('setup'); }
  function startSession() { const question = demoQuestion(language, mode, 0, topic); setSession(createSession(language, mode, level, topic, question)); setTranscript(''); setAudio(null); setSeconds(0); setNotice(''); setPage('speaking'); }
  function speakQuestion() { if (!('speechSynthesis' in window) || !session) return; speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(session.question); utterance.lang = languages[session.language].speechLocale; utterance.rate = session.language === 'ja' && session.level === 'Beginner' ? 0.83 : 0.95; speechSynthesis.speak(utterance); }
  async function beginRecording() { setNotice(''); try { const next = new AudioRecorder(); await next.start(); recorder.current = next; setAudio(null); setTranscript(''); setSeconds(0); setRecording(true); setPaused(false); setSession(s => s && speakingReducer(s, { type: 'STATUS', status: 'recording' })); timer.current = setInterval(() => setSeconds(n => n + 1), 1000); } catch (error) { setNotice(error instanceof Error ? error.message : 'Microphone unavailable'); } }
  function togglePause() { if (!recorder.current) return; if (paused) recorder.current.resume(); else recorder.current.pause(); setPaused(!paused); }
  async function finishRecording() { if (!recorder.current) return; if (timer.current) clearInterval(timer.current); setRecording(false); setPaused(false); setBusy(true); setSession(s => s && speakingReducer(s, { type: 'STATUS', status: 'processing' })); try { const result = await recorder.current.stop(); setAudio(result.blob); setSeconds(result.seconds); const form = new FormData(); form.append('audio', result.blob, result.blob.type.includes('mp4') ? 'answer.mp4' : 'answer.webm'); form.append('language', language); const response = await fetch('/api/transcribe', { method: 'POST', headers: accessCode ? { 'x-beta-access-code': accessCode } : undefined, body: form }); const data = await response.json(); if (response.ok && data.transcript) setTranscript(data.transcript); else setNotice(data.error === 'AI_NOT_CONFIGURED' ? 'Demo mode: audio saved locally. Type what you said to continue; no automatic transcription.' : `${data.error || 'Transcription unavailable'}. Type what you said to continue.`); } catch { setNotice('Recording could not be processed. Please try again.'); } finally { setBusy(false); setSession(s => s && speakingReducer(s, { type: 'STATUS', status: 'listening' })); } }
  async function submitAnswer() { if (!session || !transcript.trim() || busy) return; setBusy(true); setNotice(''); try { const audioId = audio ? crypto.randomUUID() : undefined; if (audioId && audio) await saveAudio(audioId, audio); const updated = speakingReducer(session, { type: 'ANSWER', transcript: transcript.trim(), audioId, durationSeconds: seconds }); setSession(updated); setAudio(null); setTranscript(''); setSeconds(0); if (updated.turns.length >= activeMode.maxTurns) { await finishSession(updated); return; } let question = demoQuestion(language, mode, updated.turns.length, topic); try { const response = await fetch('/api/ai', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(accessCode ? { 'x-beta-access-code': accessCode } : {}) }, body: JSON.stringify({ action: 'next', provider: textProvider, language, mode, level, topic, turns: updated.turns }) }); const data = await response.json(); if (response.ok && data.question) question = data.question; else if (data.error !== 'AI_NOT_CONFIGURED') setNotice('AI unavailable. Using demo question.'); } catch { setNotice('Offline: using demo question.'); } setSession(s => s && speakingReducer(s, { type: 'QUESTION', question })); } catch { setNotice('Could not save answer. Try again.'); } finally { setBusy(false); } }
  async function finishSession(current: Session | null = session) { if (!current || busy && current === session) return; setBusy(true); setNotice(''); let evaluation = demoEvaluation(current.language, current.turns); if (current.turns.length) { try { const response = await fetch('/api/ai', { method: 'POST', headers: { 'Content-Type': 'application/json', ...(accessCode ? { 'x-beta-access-code': accessCode } : {}) }, body: JSON.stringify({ action: 'evaluate', provider: textProvider, language: current.language, mode: current.mode, level: current.level, topic: current.topic, turns: current.turns }) }); const data = await response.json(); if (response.ok && data.evaluation) evaluation = data.evaluation; else if (data.error !== 'AI_NOT_CONFIGURED') setNotice('AI unavailable. Showing demo review.'); } catch { setNotice('Offline: showing demo review.'); } } const done = speakingReducer(current, { type: 'EVALUATE', evaluation }); setSession(done); saveSession(done); setPage('result'); setBusy(false); }
  function retry(turn: Turn) { if (!session) return; setSession(s => s && speakingReducer(s, { type: 'RETRY', turnId: turn.id })); setTranscript(''); setAudio(null); setSeconds(0); setNotice('Same question, new attempt.'); setPage('speaking'); }
  async function playAudio(id: string) { const blob = await getAudio(id); if (!blob) { setNotice('Recording no longer available on this device.'); return; } const url = URL.createObjectURL(blob); const player = new Audio(url); player.onended = () => URL.revokeObjectURL(url); player.play().catch(() => setNotice('Playback unavailable.')); }
  function openSession(item: Session) { setSession(item); setLanguage(item.language); setMode(item.mode); setLevel(item.level); setTopic(item.topic); setPage(item.evaluation ? 'result' : 'speaking'); }

  return <div className="app-shell"><div className="app-frame">
    {page !== 'speaking' && page !== 'result' && <header className="topbar"><div className="brand"><span className="brand-mark"><AudioLines size={20} strokeWidth={2.5} /></span><span>oral<span className="brand-dot">.</span></span></div><div className="topbar-tools"><span className="topbar-caption">{text.studio}</span><button className="settings-button" aria-label={text.settings} onClick={() => setSettingsOpen(true)}><Settings2 size={18} /></button></div></header>}
    {settingsOpen && <div className="settings-backdrop" role="presentation" onClick={() => setSettingsOpen(false)}><section className="settings-sheet" role="dialog" aria-modal="true" aria-label={text.settings} onClick={event => event.stopPropagation()}><div className="settings-head"><div><span className="section-kicker">ORAL</span><h2>{text.settings}</h2><p>{text.settingsHint}</p></div><button className="settings-close" aria-label={text.close} onClick={() => setSettingsOpen(false)}><X size={19} /></button></div><div className="preference-module"><div className="module-title"><Languages size={18} /><span>{text.interfaceLanguage}</span></div><div className="language-options">{interfaceLanguages.map(item => <button key={item.id} className={uiLanguage === item.id ? 'selected' : ''} onClick={() => setUiLanguage(item.id)}>{item.label}<Check size={16} /></button>)}</div></div><div className="preference-module"><div className="module-title"><Sparkles size={18} /><span>AI feedback provider</span></div><div className="provider-options">{(['openai', 'deepseek', 'glm'] as const).map(provider => <button key={provider} className={textProvider === provider ? 'selected' : ''} onClick={() => setTextProvider(provider)}>{provider === 'glm' ? 'GLM' : provider === 'openai' ? 'OpenAI' : 'DeepSeek'}<Check size={16} /></button>)}</div><p className="provider-note">Speech transcription uses OpenAI. API keys stay server-side.</p><label className="access-code-label" htmlFor="beta-access-code">Beta access code</label><input id="beta-access-code" className="access-code-input" value={accessCode} onChange={event => setAccessCode(event.target.value)} autoComplete="off" /></div><div className="preference-module"><div className="module-title"><Sun size={18} /><span>{text.appearance}</span></div><div className="theme-options"><button className={theme === 'light' ? 'selected' : ''} onClick={() => setTheme('light')}><span className="theme-swatch light-swatch"><i /><i /><i /><i /><i /></span><span>{text.light}</span><Sun size={16} /></button><button className={theme === 'dark' ? 'selected' : ''} onClick={() => setTheme('dark')}><span className="theme-swatch dark-swatch"><i /><i /><i /><i /><i /></span><span>{text.dark}</span><Moon size={16} /></button></div></div></section></div>}
    <main className={`main-content ${page === 'speaking' || page === 'result' ? 'full-height' : ''}`}>
      {page === 'home' && <><div className="hero"><div className="eyebrow"><span className="live-dot" /> {text.daily}</div><h1>{text.voice}<br /><em>{text.further}</em></h1><p>{text.intro}</p><div className="hero-art" aria-hidden="true"><div className="art-ring ring-one" /><div className="art-ring ring-two" /><AudioLines size={56} strokeWidth={1.5} /></div></div><div className="section-head"><div><span className="section-kicker">{text.begin}</span><h2>{text.choose}</h2></div><span className="section-number">01 / 02</span></div><div className="language-list">{(['en', 'ja'] as const).map(id => <button className={`language-card ${id}`} key={id} onClick={() => chooseLanguage(id)}><span className="language-symbol">{languages[id].flag}</span><span className="language-copy"><strong>{languages[id].name} <span className="native-name">{id === 'ja' ? '日本語' : ''}</span></strong><small>{languages[id].description}</small></span><span className="round-arrow"><ArrowRight size={19} /></span></button>)}</div><div className="quick-stats"><div><span>{text.journey}</span><strong>{stats.sessions.toString().padStart(2, '0')}</strong><small>{text.sessions}</small></div><div><span>&nbsp;</span><strong>{stats.minutes.toString().padStart(2, '0')}</strong><small>{text.minutes}</small></div><div><span>&nbsp;</span><strong>—</strong><small>{text.streak}</small></div></div><p className="fine-print">* Streak tracking comes with account sync.</p>{sessions.length > 0 && <><div className="section-head compact"><h2>Pick up where you left off</h2></div><button className="recent-card" onClick={() => openSession(sessions[0])}><span className="recent-icon">{languages[sessions[0].language].flag}</span><span><strong>{modes[sessions[0].mode].title}</strong><small>{new Date(sessions[0].startedAt).toLocaleDateString()} · {sessions[0].turns.length} answers</small></span><ChevronRight size={18} /></button></>}</>}
      {page === 'practice' && <><button className="text-back" onClick={() => setPage('home')}><ArrowLeft size={18} /> Languages</button><div className="page-intro"><span className="section-kicker">{config.flag} / {config.nativeName.toUpperCase()}</span><h1>What will you<br /><em>practice today?</em></h1><p>Choose a space to speak. Your pace, your progress.</p></div><div className="language-switch"><button className={language === 'en' ? 'selected' : ''} onClick={() => chooseLanguage('en')}>English</button><button className={language === 'ja' ? 'selected' : ''} onClick={() => chooseLanguage('ja')}>日本語</button></div><div className="mode-list">{config.modes.map(id => { const item = modes[id]; const Icon = iconMap[id]; return <button key={id} disabled={!item.enabled} className={`mode-card ${!item.enabled ? 'disabled' : ''}`} onClick={() => chooseMode(id)}><span className="mode-icon"><Icon size={23} strokeWidth={1.8} /></span><span className="mode-copy"><strong>{item.title}</strong><small>{item.short}</small></span>{item.enabled ? <ChevronRight size={19} /> : <span className="soon">SOON</span>}</button>; })}</div>{language === 'ja' && <div className="info-note"><CircleHelp size={18} /><span>Levels are learning guides, not official JLPT speaking scores.</span></div>}</>}
      {page === 'setup' && <><button className="text-back" onClick={() => setPage('practice')}><ArrowLeft size={18} /> Practice modes</button><div className="page-intro"><span className="section-kicker">PERSONALIZE YOUR SESSION</span><h1>Make this<br /><em>your moment.</em></h1><p>A few choices help your partner meet you where you are.</p></div><div className="setup-panel"><div className="setup-mode"><span className="mode-icon"><Settings2 size={22} /></span><span><small>SELECTED PRACTICE</small><strong>{activeMode.title}</strong></span></div><label className="field-label" htmlFor="level">Your level</label><select id="level" value={level} onChange={e => setLevel(e.target.value)}>{config.levels.map(item => <option key={item}>{item}</option>)}</select><label className="field-label" htmlFor="topic">Focus / scenario</label><select id="topic" value={topic} onChange={e => setTopic(e.target.value)}>{(config.topics[mode] || config.topics.daily).map(item => <option key={item}>{item}</option>)}</select><div className="session-details"><span><Clock3 size={16} /> 5–10 minutes</span><span><Mic size={16} /> Voice first</span></div></div><div className="info-note"><Sparkles size={18} /><span>{activeMode.description}</span></div><button className="primary-button" onClick={startSession}>Start speaking <ArrowRight size={19} /></button><p className="center-note">Microphone access is requested when you start recording.</p></>}
      {page === 'speaking' && session && <><div className="session-top"><button className="icon-button" aria-label="Back" onClick={() => setPage('practice')}><ArrowLeft size={20} /></button><span className="session-title">{config.name} <span>/</span> {activeMode.title}</span><button className="finish-link" disabled={busy || recording} onClick={() => finishSession()}>Finish</button></div><div className="session-progress"><span style={{ width: `${Math.min(100, (session.turns.length / activeMode.maxTurns) * 100)}%` }} /></div><div className="speaking-body"><div className="partner-badge"><span className="avatar"><AudioLines size={30} /></span><div><strong>{activeMode.role}</strong><small><span className="live-dot" /> {busy ? 'THINKING' : recording ? 'LISTENING' : 'READY TO TALK'}</small></div></div><div className="question-card"><span className="question-label">QUESTION {session.turns.length + 1} <span>·</span> {topic}</span><h2>{session.question}</h2><button className="listen-button" onClick={speakQuestion}><Volume2 size={17} /> Listen to question</button></div><div className="answer-zone"><span className="section-kicker">YOUR RESPONSE</span>{recording ? <><div className="recording-indicator"><span className="pulse-dot" /> {paused ? 'PAUSED' : 'RECORDING'} <strong>{formatTime(seconds)}</strong></div><div className="recorder-controls"><button className="pause-button" onClick={togglePause}>{paused ? <Play size={18} /> : <Pause size={18} />}{paused ? 'Resume' : 'Pause'}</button><button className="stop-button" onClick={finishRecording}><Square size={17} fill="currentColor" /> Finish answer</button></div></> : <><button className="mic-button" onClick={beginRecording} disabled={busy} aria-label="Start recording"><Mic size={38} strokeWidth={1.7} /></button><span className="mic-caption">Tap to start speaking</span></>}{audioUrl && <audio className="audio-player" controls src={audioUrl} />}{!recording && <><label className="transcript-label" htmlFor="transcript">Transcript {audio ? <span>· review / edit</span> : <span>· type to practice without audio</span>}</label><textarea id="transcript" value={transcript} onChange={e => setTranscript(e.target.value)} rows={3} placeholder={language === 'ja' ? 'ここに話した内容が表示されます…' : 'What you said will appear here…'} /><button className="primary-button submit-button" disabled={!transcript.trim() || busy} onClick={submitAnswer}>{busy ? 'Processing…' : 'Continue conversation'} <ArrowRight size={19} /></button></>}</div>{notice && <div className="notice" role="status">{notice}</div>}{session.turns.length > 0 && <div className="session-count">{session.turns.length} answer{session.turns.length === 1 ? '' : 's'} saved · up to {activeMode.maxTurns} turns</div>}</div></>}
      {page === 'result' && session && <><div className="session-top"><button className="icon-button" aria-label="Home" onClick={() => setPage('home')}><ArrowLeft size={20} /></button><span className="session-title">SESSION REVIEW</span><span className="finish-link muted">{config.flag}</span></div><div className="result-intro"><span className="complete-icon"><Check size={27} /></span><span className="section-kicker">PRACTICE COMPLETE</span><h1>Every word<br /><em>counts.</em></h1><p>{session.turns.length} answers · {formatTime(session.turns.reduce((n, t) => n + t.durationSeconds, 0))} speaking time</p></div><div className="feedback-card"><div className="feedback-head"><WandSparkles size={19} /><strong>{session.evaluation?.model === 'ai' ? 'AI feedback' : 'Demo review'}</strong></div><p>{session.evaluation?.summary || 'No review yet.'}</p>{session.evaluation?.scores?.length ? <div className="score-list">{session.evaluation.scores.map(score => <div key={score.key}><div className="score-heading"><span>{score.label}</span><strong>{score.value.toFixed(1)} / 10</strong></div><div className="score-track"><span style={{ width: `${score.value * 10}%` }} /></div><small>{score.note}</small></div>)}</div> : <p className="feedback-disclaimer">No numerical score in demo mode. Pronunciation needs actual audio analysis.</p>}{session.evaluation?.improvements?.length ? <div className="improve-block"><strong>Next focus</strong>{session.evaluation.improvements.map((item, index) => <p key={index}>{item}</p>)}</div> : null}</div><div className="section-head compact"><h2>Your answers</h2><span className="section-number">{session.turns.length.toString().padStart(2, '0')}</span></div><div className="turn-list">{session.turns.map((turn, index) => <div className="turn-card" key={turn.id}><div className="turn-meta"><span>ANSWER {index + 1} · ATTEMPT {turn.attempt}</span><span>{formatTime(turn.durationSeconds)}</span></div><strong>{turn.question}</strong><p>{turn.transcript}</p><div className="turn-actions">{turn.audioId && <button onClick={() => playAudio(turn.audioId!)}><Play size={15} /> Play audio</button>}<button onClick={() => retry(turn)}><RotateCcw size={15} /> Retry question</button></div></div>)}</div>{notice && <div className="notice" role="status">{notice}</div>}<button className="primary-button" onClick={() => setPage('practice')}>Practice again <ArrowRight size={19} /></button></>}
      {page === 'progress' && <><div className="page-intro progress-intro"><span className="section-kicker">THE BIG PICTURE</span><h1>See how far<br /><em>you’ve come.</em></h1><p>Every conversation builds your confidence.</p></div><div className="language-switch three"><button className={tab === 'all' ? 'selected' : ''} onClick={() => setTab('all')}>Overall</button><button className={tab === 'en' ? 'selected' : ''} onClick={() => setTab('en')}>English</button><button className={tab === 'ja' ? 'selected' : ''} onClick={() => setTab('ja')}>日本語</button></div><div className="progress-grid"><div><Clock3 size={20} /><strong>{currentStats.minutes}</strong><span>minutes spoken</span></div><div><AudioLines size={20} /><strong>{currentStats.sessions}</strong><span>sessions</span></div><div><BarChart3 size={20} /><strong>{currentStats.average === null ? '—' : currentStats.average}</strong><span>avg. AI indicator</span></div></div><div className="section-head compact"><h2>Focus areas</h2></div>{currentStats.weaknesses.length ? <div className="chip-list">{currentStats.weaknesses.map(item => <span key={item}>{item}</span>)}</div> : <div className="empty-state"><Target size={25} /><strong>No focus areas yet</strong><p>Complete an AI-reviewed session to see patterns worth practicing.</p></div>}<div className="section-head compact"><h2>Recent practice</h2></div>{sessions.filter(s => tab === 'all' || s.language === tab).length ? sessions.filter(s => tab === 'all' || s.language === tab).slice(0, 8).map(item => <button className="recent-card" key={item.id} onClick={() => openSession(item)}><span className="recent-icon">{languages[item.language].flag}</span><span><strong>{modes[item.mode].title}</strong><small>{new Date(item.startedAt).toLocaleDateString()} · {item.turns.length} answers</small></span><ChevronRight size={18} /></button>) : <p className="empty-copy">Your first session starts here.</p>}</>}
      {page === 'profile' && <><div className="page-intro"><span className="section-kicker">YOUR SPACE</span><h1>Practice that<br /><em>feels personal.</em></h1><p>Local-first MVP profile. Your data stays in this browser.</p></div><div className="profile-card"><span className="profile-avatar"><UserRound size={28} /></span><div><strong>Guest speaker</strong><small>No account connected</small></div></div><div className="section-head compact"><h2>Language profiles</h2></div>{(['en', 'ja'] as const).map(id => <div className="profile-language" key={id}><span className="recent-icon">{languages[id].flag}</span><span><strong>{languages[id].name}</strong><small>{getStats(sessions, id).sessions} sessions on this device</small></span></div>)}<div className="info-note"><CircleHelp size={18} /><span>History and audio are stored only on this device. Clearing site data removes them. Supabase sync is planned, not active.</span></div><div className="section-head compact"><h2>About Oral</h2></div><p className="about-copy">One speaking engine. Multiple languages. A quieter place to practice out loud.</p></>}
    </main>
    {page !== 'speaking' && page !== 'result' && <nav className="bottom-nav" aria-label="Main navigation">{([{ id: 'home', label: text.home, Icon: Home }, { id: 'practice', label: text.practice, Icon: Headphones }, { id: 'progress', label: text.progress, Icon: BarChart3 }, { id: 'profile', label: text.profile, Icon: UserRound }] as const).map(item => <button key={item.id} onClick={() => setPage(item.id)} className={page === item.id || page === 'setup' && item.id === 'practice' ? 'active' : ''}><item.Icon size={21} strokeWidth={1.8} /><span>{item.label}</span></button>)}</nav>}
  </div></div>;
}
