export type UiLanguage = 'zh-CN' | 'en' | 'zh-HK' | 'ja';

const en = {
  provider: 'AI feedback provider', providerNote: 'Speech transcription uses OpenAI. API keys stay server-side.', accessCode: 'Beta access code', streakNote: 'Streak tracking comes with account sync.', resume: 'Pick up where you left off',
  languages: 'Languages', today: 'What will you', todayEm: 'practice today?', chooseSpace: 'Choose a space to speak. Your pace, your progress.', soon: 'SOON', jlptNote: 'Levels are learning guides, not official JLPT speaking scores.',
  practiceModes: 'Practice modes', personalize: 'PERSONALIZE YOUR SESSION', makeMoment: 'Make this', momentEm: 'your moment.', choices: 'A few choices help your partner meet you where you are.', selected: 'SELECTED PRACTICE', level: 'Your level', focus: 'Focus / scenario', minutesRange: '5–10 minutes', voiceFirst: 'Voice first', start: 'Start speaking', micNote: 'Microphone access is requested when you start recording.',
  back: 'Back', finish: 'Finish', thinking: 'THINKING', listening: 'LISTENING', ready: 'READY TO TALK', question: 'QUESTION', listenQuestion: 'Listen to question', response: 'YOUR RESPONSE', paused: 'PAUSED', recording: 'RECORDING', resumeRecording: 'Resume', pause: 'Pause', finishAnswer: 'Finish answer', startRecording: 'Start recording', tapStart: 'Tap to start speaking', transcript: 'Transcript', review: 'review / edit', typePractice: 'type to practice without audio', placeholder: 'What you said will appear here…', processing: 'Processing…', continue: 'Continue conversation', saved: 'saved', upTo: 'up to', answers: 'answers', turns: 'turns',
  sessionReview: 'SESSION REVIEW', complete: 'PRACTICE COMPLETE', everyWord: 'Every word', counts: 'counts.', speakingTime: 'speaking time', aiFeedback: 'AI feedback', demoReview: 'Demo review', noReview: 'No review yet.', noScore: 'No numerical score in demo mode. Pronunciation needs actual audio analysis.', nextFocus: 'Next focus', yourAnswers: 'Your answers', answer: 'ANSWER', attempt: 'ATTEMPT', playAudio: 'Play audio', retry: 'Retry question', practiceAgain: 'Practice again',
  bigPicture: 'THE BIG PICTURE', seeProgress: 'See how far', progressEm: 'you’ve come.', confidence: 'Every conversation builds your confidence.', overall: 'Overall', english: 'English', japanese: '日本語', minutesSpoken: 'minutes spoken', sessionCount: 'sessions', aiAverage: 'avg. AI indicator', focusAreas: 'Focus areas', noFocus: 'No focus areas yet', focusHint: 'Complete an AI-reviewed session to see patterns worth practicing.', recent: 'Recent practice', firstSession: 'Your first session starts here.',
  yourSpace: 'YOUR SPACE', personal: 'Practice that', personalEm: 'feels personal.', localProfile: 'Local-first MVP profile. Your data stays in this browser.', guest: 'Guest speaker', noAccount: 'No account connected', languageProfiles: 'Language profiles', deviceSessions: 'sessions on this device', historyNote: 'History and audio are stored only on this device. Clearing site data removes them. Supabase sync is planned, not active.', about: 'About Oral', aboutCopy: 'One speaking engine. Multiple languages. A quieter place to practice out loud.',
  unavailable: 'AI unavailable. Using demo question.', offline: 'Offline: using demo question.', saveFailed: 'Could not save answer. Try again.', recordFailed: 'Recording could not be processed. Please try again.', micUnavailable: 'Microphone unavailable', transcription: 'Transcription unavailable. Type what you said to continue.', demoAudio: 'Demo mode: audio saved locally. Type what you said to continue; no automatic transcription.', sameQuestion: 'Same question, new attempt.', audioMissing: 'Recording no longer available on this device.', playback: 'Playback unavailable.', demoFeedback: 'AI unavailable. Showing demo review.', demoOffline: 'Offline: showing demo review.', enLearn: 'Build confidence, one conversation at a time.', jaLearn: 'Japanese for real-life conversations.',
  beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', navigation: 'Main navigation',
};

type Copy = typeof en;
export const uiExtra: Record<UiLanguage, Copy> = {
  en,
  'zh-CN': { provider:'AI 反馈服务商', providerNote:'语音转写使用 OpenAI；密钥仅保留在服务器。', accessCode:'测试访问码', streakNote:'连续练习需要账户同步。', resume:'继续上次练习', languages:'语言', today:'今天想练', todayEm:'什么？', chooseSpace:'选择练习场景，按自己的节奏开口。', soon:'即将推出', jlptNote:'级别仅作学习参考，不是官方 JLPT 口语成绩。', practiceModes:'练习模式', personalize:'自定义本次练习', makeMoment:'把这一刻', momentEm:'变成你的。', choices:'几个选择，让陪练更贴合你的节奏。', selected:'已选练习', level:'你的水平', focus:'重点 / 场景', minutesRange:'5–10 分钟', voiceFirst:'优先语音', start:'开始练习', micNote:'开始录音时会请求麦克风权限。', back:'返回', finish:'结束', thinking:'正在思考', listening:'正在聆听', ready:'准备开口', question:'问题', listenQuestion:'播放问题', response:'你的回答', paused:'已暂停', recording:'录音中', resumeRecording:'继续', pause:'暂停', finishAnswer:'完成回答', startRecording:'开始录音', tapStart:'点击开始说话', transcript:'转写文本', review:'检查 / 修改', typePractice:'不录音也可以直接输入练习', placeholder:'你说的内容会显示在这里…', processing:'处理中…', continue:'继续对话', saved:'已保存', upTo:'最多', answers:'个回答', turns:'轮', sessionReview:'练习回顾', complete:'练习完成', everyWord:'每个词', counts:'都重要。', speakingTime:'说话时长', aiFeedback:'AI 反馈', demoReview:'演示回顾', noReview:'暂时没有反馈。', noScore:'演示模式不提供数值评分；发音需要真实音频分析。', nextFocus:'下一步重点', yourAnswers:'你的回答', answer:'回答', attempt:'尝试', playAudio:'播放录音', retry:'重试此题', practiceAgain:'再次练习', bigPicture:'整体情况', seeProgress:'看看你', progressEm:'走了多远。', confidence:'每次对话都会建立你的自信。', overall:'全部', english:'英语', japanese:'日语', minutesSpoken:'说话分钟', sessionCount:'练习次数', aiAverage:'AI 平均指标', focusAreas:'重点领域', noFocus:'暂时没有重点领域', focusHint:'完成一次 AI 反馈练习后，这里会显示值得加强的模式。', recent:'最近练习', firstSession:'从第一次练习开始。', yourSpace:'你的空间', personal:'练习应当', personalEm:'更贴合你。', localProfile:'本地优先的测试版资料。数据保留在此浏览器。', guest:'访客练习者', noAccount:'未连接账户', languageProfiles:'语言资料', deviceSessions:'次练习（此设备）', historyNote:'历史记录和录音仅保存在此设备。清除网站数据会删除它们。Supabase 同步尚未启用。', about:'关于 Oral', aboutCopy:'一个口语引擎，多种语言；一个更安静的开口练习空间。', unavailable:'AI 暂不可用，已改用演示问题。', offline:'离线状态：已改用演示问题。', saveFailed:'无法保存回答，请重试。', recordFailed:'录音无法处理，请重试。', micUnavailable:'麦克风不可用', transcription:'转写不可用，请输入你说的内容后继续。', demoAudio:'演示模式：录音已保存在本机。请输入你说的内容后继续；不会自动转写。', sameQuestion:'同一问题，新的尝试。', audioMissing:'此设备上的录音已不可用。', playback:'无法播放录音。', demoFeedback:'AI 暂不可用，显示演示反馈。', demoOffline:'离线状态：显示演示反馈。', enLearn:'建立信心，一次对话一步。', jaLearn:'面向真实生活的日语会话。', beginner:'初级', intermediate:'中级', advanced:'高级', navigation:'主导航' },
  'zh-HK': { provider:'AI 回饋服務商', providerNote:'語音轉寫使用 OpenAI；金鑰只保留在伺服器。', accessCode:'測試存取碼', streakNote:'連續練習需要帳戶同步。', resume:'繼續上次練習', languages:'語言', today:'今天想練', todayEm:'甚麼？', chooseSpace:'選擇練習情境，按自己的節奏開口。', soon:'即將推出', jlptNote:'級別只作學習參考，並非官方 JLPT 口語成績。', practiceModes:'練習模式', personalize:'自訂本次練習', makeMoment:'把這一刻', momentEm:'變成你的。', choices:'幾個選擇，讓陪練更貼合你的節奏。', selected:'已選練習', level:'你的程度', focus:'重點 / 情境', minutesRange:'5–10 分鐘', voiceFirst:'優先語音', start:'開始練習', micNote:'開始錄音時會要求麥克風權限。', back:'返回', finish:'結束', thinking:'思考中', listening:'聆聽中', ready:'準備開口', question:'問題', listenQuestion:'播放問題', response:'你的回答', paused:'已暫停', recording:'錄音中', resumeRecording:'繼續', pause:'暫停', finishAnswer:'完成回答', startRecording:'開始錄音', tapStart:'點擊開始說話', transcript:'轉寫文字', review:'檢查 / 修改', typePractice:'不錄音也可以直接輸入練習', placeholder:'你說的內容會顯示在這裡…', processing:'處理中…', continue:'繼續對話', saved:'已儲存', upTo:'最多', answers:'個回答', turns:'輪', sessionReview:'練習回顧', complete:'練習完成', everyWord:'每個字', counts:'都重要。', speakingTime:'說話時長', aiFeedback:'AI 回饋', demoReview:'示範回顧', noReview:'暫時沒有回饋。', noScore:'示範模式不提供數值評分；發音需要真實音訊分析。', nextFocus:'下一步重點', yourAnswers:'你的回答', answer:'回答', attempt:'嘗試', playAudio:'播放錄音', retry:'重試此題', practiceAgain:'再次練習', bigPicture:'整體情況', seeProgress:'看看你', progressEm:'走了多遠。', confidence:'每次對話都會建立你的自信。', overall:'全部', english:'英語', japanese:'日語', minutesSpoken:'說話分鐘', sessionCount:'練習次數', aiAverage:'AI 平均指標', focusAreas:'重點領域', noFocus:'暫時沒有重點領域', focusHint:'完成一次 AI 回饋練習後，這裡會顯示值得加強的模式。', recent:'最近練習', firstSession:'從第一次練習開始。', yourSpace:'你的空間', personal:'練習應當', personalEm:'更貼合你。', localProfile:'本地優先的測試版資料。資料保留在此瀏覽器。', guest:'訪客練習者', noAccount:'未連接帳戶', languageProfiles:'語言資料', deviceSessions:'次練習（此裝置）', historyNote:'歷史記錄和錄音只保存在此裝置。清除網站資料會刪除它們。Supabase 同步尚未啟用。', about:'關於 Oral', aboutCopy:'一個口語引擎，多種語言；一個更安靜的開口練習空間。', unavailable:'AI 暫不可用，已改用示範問題。', offline:'離線狀態：已改用示範問題。', saveFailed:'無法儲存回答，請重試。', recordFailed:'錄音無法處理，請重試。', micUnavailable:'麥克風不可用', transcription:'轉寫不可用，請輸入你說的內容後繼續。', demoAudio:'示範模式：錄音已保存在本機。請輸入你說的內容後繼續；不會自動轉寫。', sameQuestion:'同一問題，新的嘗試。', audioMissing:'此裝置上的錄音已不可用。', playback:'無法播放錄音。', demoFeedback:'AI 暫不可用，顯示示範回饋。', demoOffline:'離線狀態：顯示示範回饋。', enLearn:'建立信心，一次對話一步。', jaLearn:'面向真實生活的日語會話。', beginner:'初級', intermediate:'中級', advanced:'高級', navigation:'主導覽' },
  ja: { provider:'AI フィードバック提供元', providerNote:'音声文字起こしは OpenAI を使用します。API キーはサーバー側だけに保存されます。', accessCode:'ベータアクセスコード', streakNote:'連続記録にはアカウント同期が必要です。', resume:'前回の練習を続ける', languages:'言語', today:'今日は何を', todayEm:'練習しますか？', chooseSpace:'話す場面を選び、自分のペースで進めましょう。', soon:'近日公開', jlptNote:'レベルは学習の目安であり、公式の JLPT スピーキング評価ではありません。', practiceModes:'練習モード', personalize:'セッションを設定', makeMoment:'この時間を', momentEm:'あなたのものに。', choices:'いくつか選ぶだけで、相手があなたに合った練習をします。', selected:'選択した練習', level:'レベル', focus:'テーマ / 場面', minutesRange:'5〜10 分', voiceFirst:'音声から始める', start:'話し始める', micNote:'録音を開始するときにマイクへのアクセスを求めます。', back:'戻る', finish:'終了', thinking:'考え中', listening:'聞いています', ready:'会話の準備完了', question:'質問', listenQuestion:'質問を聞く', response:'あなたの回答', paused:'一時停止中', recording:'録音中', resumeRecording:'再開', pause:'一時停止', finishAnswer:'回答を終了', startRecording:'録音を開始', tapStart:'タップして話し始める', transcript:'文字起こし', review:'確認 / 編集', typePractice:'音声なしで入力練習', placeholder:'話した内容がここに表示されます…', processing:'処理中…', continue:'会話を続ける', saved:'保存済み', upTo:'最大', answers:'回答', turns:'ターン', sessionReview:'セッションレビュー', complete:'練習完了', everyWord:'すべての言葉に', counts:'意味がある。', speakingTime:'発話時間', aiFeedback:'AI フィードバック', demoReview:'デモレビュー', noReview:'まだレビューはありません。', noScore:'デモモードでは数値評価はありません。発音には実際の音声分析が必要です。', nextFocus:'次の重点', yourAnswers:'あなたの回答', answer:'回答', attempt:'回目', playAudio:'録音を再生', retry:'この質問を再挑戦', practiceAgain:'もう一度練習', bigPicture:'全体の記録', seeProgress:'どこまで', progressEm:'進んだか見よう。', confidence:'会話のたびに自信が育ちます。', overall:'すべて', english:'英語', japanese:'日本語', minutesSpoken:'発話分数', sessionCount:'セッション数', aiAverage:'AI 平均指標', focusAreas:'重点項目', noFocus:'まだ重点項目はありません', focusHint:'AI レビュー付きのセッションを完了すると、練習すべき傾向が表示されます。', recent:'最近の練習', firstSession:'最初の練習はここから。', yourSpace:'あなたの空間', personal:'自分らしい', personalEm:'練習を。', localProfile:'ローカル優先のテスト版プロフィールです。データはこのブラウザに残ります。', guest:'ゲストスピーカー', noAccount:'アカウント未接続', languageProfiles:'言語プロフィール', deviceSessions:'件のセッション（この端末）', historyNote:'履歴と音声はこの端末だけに保存されます。サイトデータを消去すると削除されます。Supabase 同期は未実装です。', about:'Oral について', aboutCopy:'一つのスピーキングエンジン、複数の言語。声に出して練習するための静かな場所。', unavailable:'AI を利用できません。デモ質問を使用します。', offline:'オフライン：デモ質問を使用します。', saveFailed:'回答を保存できませんでした。もう一度お試しください。', recordFailed:'録音を処理できませんでした。もう一度お試しください。', micUnavailable:'マイクを利用できません', transcription:'文字起こしを利用できません。話した内容を入力して続けてください。', demoAudio:'デモモード：音声は端末に保存されました。続けるには話した内容を入力してください。自動文字起こしはありません。', sameQuestion:'同じ質問で新しい試行です。', audioMissing:'この端末の録音は利用できません。', playback:'音声を再生できません。', demoFeedback:'AI を利用できません。デモレビューを表示します。', demoOffline:'オフライン：デモレビューを表示します。', enLearn:'会話を重ねて自信をつけよう。', jaLearn:'実生活のための日本語会話。', beginner:'初級', intermediate:'中級', advanced:'上級', navigation:'メインナビゲーション' },
};

export const modeUi: Record<UiLanguage, Record<string, { title: string; short: string; role: string; description: string }>> = {
  en: {},
  'zh-CN': {
    ielts:{title:'雅思口语',short:'考试场景练习',role:'雅思考官',description:'按雅思口语题型练习；反馈不是官方分数。'}, toefl:{title:'托福口语',short:'考试场景练习',role:'托福考官',description:'按托福口语题型练习；反馈不是官方分数。'}, daily:{title:'日常对话',short:'练习日常表达',role:'对话伙伴',description:'轻松自然地谈谈你的生活。'}, scenario:{title:'情景练习',short:'真实生活场景',role:'情景伙伴',description:'与角色扮演伙伴练习实际场景。'}, topic:{title:'话题练习',short:'深入讨论',role:'对话伙伴',description:'围绕一个话题继续深入。'}, 'free-talk':{title:'自由对话',short:'开放式交流',role:'对话伙伴',description:'自主选择对话方向。'}, interview:{title:'面试练习',short:'即将推出',role:'面试官',description:'练习日语面试。'}, weakness:{title:'薄弱项练习',short:'即将推出',role:'教练',description:'针对过去练习中的弱项。'},
  },
  'zh-HK': {
    ielts:{title:'雅思口語',short:'考試情境練習',role:'雅思考官',description:'按雅思口語題型練習；回饋並非官方分數。'}, toefl:{title:'托福口語',short:'考試情境練習',role:'托福考官',description:'按托福口語題型練習；回饋並非官方分數。'}, daily:{title:'日常對話',short:'練習日常表達',role:'對話夥伴',description:'輕鬆自然地談談你的生活。'}, scenario:{title:'情境練習',short:'真實生活情境',role:'情境夥伴',description:'與角色扮演夥伴練習實際情境。'}, topic:{title:'話題練習',short:'深入討論',role:'對話夥伴',description:'圍繞一個話題繼續深入。'}, 'free-talk':{title:'自由對話',short:'開放式交流',role:'對話夥伴',description:'自主選擇對話方向。'}, interview:{title:'面試練習',short:'即將推出',role:'面試官',description:'練習日語面試。'}, weakness:{title:'弱項練習',short:'即將推出',role:'教練',description:'針對過去練習中的弱項。'},
  },
  ja: {
    ielts:{title:'IELTS スピーキング',short:'試験形式の練習',role:'IELTS 試験官',description:'IELTS 形式で練習します。公式スコアではありません。'}, toefl:{title:'TOEFL スピーキング',short:'試験形式の練習',role:'TOEFL 試験官',description:'TOEFL 形式で練習します。公式スコアではありません。'}, daily:{title:'日常会話',short:'日常の表現',role:'会話パートナー',description:'日々のことを自然な流れで話しましょう。'}, scenario:{title:'場面練習',short:'実生活の場面',role:'場面パートナー',description:'ロールプレイで実際の場面を練習します。'}, topic:{title:'テーマ練習',short:'深く話す',role:'会話パートナー',description:'一つのテーマを掘り下げます。'}, 'free-talk':{title:'自由会話',short:'自由に話す',role:'会話パートナー',description:'会話の方向を自分で選びます。'}, interview:{title:'面接練習',short:'近日公開',role:'面接官',description:'日本語の面接を練習します。'}, weakness:{title:'弱点練習',short:'近日公開',role:'コーチ',description:'過去のセッションから弱点を練習します。'},
  },
};

export const topicUi: Record<UiLanguage, Record<string, string>> = {
  en: { '自己紹介':'Self-introduction', '食べ物':'Food', '趣味':'Hobbies', '旅行':'Travel', 'コンビニ':'Convenience store', 'レストラン':'Restaurant', '駅':'Station', 'ホテル':'Hotel', '職場':'Workplace', '文化':'Culture', '教育':'Education', '健康':'Health', '自由会話':'Open conversation' },
  'zh-CN': { 'Everyday life':'日常生活', 'Food & drink':'饮食', 'Travel':'旅行', 'Work & study':'工作与学习', 'Full mock · Parts 1–3':'完整模拟 · 第一至三部分', 'Part 1 · Familiar topics':'第一部分 · 熟悉话题', 'Part 2 · Long turn':'第二部分 · 长篇陈述', 'Part 3 · Discussion':'第三部分 · 讨论', 'Technology':'科技', 'Culture':'文化', 'Education':'教育', 'Open conversation':'开放对话', '自己紹介':'自我介绍', '食べ物':'饮食', '趣味':'兴趣', '旅行':'旅行', 'コンビニ':'便利店', 'レストラン':'餐厅', '駅':'车站', 'ホテル':'酒店', '職場':'职场', '文化':'文化', '教育':'教育', '健康':'健康', '自由会話':'自由对话' },
  'zh-HK': { 'Everyday life':'日常生活', 'Food & drink':'飲食', 'Travel':'旅行', 'Work & study':'工作與學習', 'Full mock · Parts 1–3':'完整模擬 · 第一至三部分', 'Part 1 · Familiar topics':'第一部分 · 熟悉話題', 'Part 2 · Long turn':'第二部分 · 長篇陳述', 'Part 3 · Discussion':'第三部分 · 討論', 'Technology':'科技', 'Culture':'文化', 'Education':'教育', 'Open conversation':'開放對話', '自己紹介':'自我介紹', '食べ物':'飲食', '趣味':'興趣', '旅行':'旅行', 'コンビニ':'便利店', 'レストラン':'餐廳', '駅':'車站', 'ホテル':'酒店', '職場':'職場', '文化':'文化', '教育':'教育', '健康':'健康', '自由会話':'自由對話' },
  ja: { 'Everyday life':'日常生活', 'Food & drink':'飲食', 'Travel':'旅行', 'Work & study':'仕事と勉強', 'Full mock · Parts 1–3':'フル模擬 · パート1〜3', 'Part 1 · Familiar topics':'パート1 · 身近な話題', 'Part 2 · Long turn':'パート2 · ロングターン', 'Part 3 · Discussion':'パート3 · ディスカッション', 'Technology':'テクノロジー', 'Culture':'文化', 'Education':'教育', 'Open conversation':'自由会話' },
};

export const levelUi: Record<UiLanguage, Record<string, string>> = {
  en: {}, 'zh-CN': { Beginner:'初级', Elementary:'基础', Intermediate:'中级', 'Upper Intermediate':'中高级', Advanced:'高级' },
  'zh-HK': { Beginner:'初級', Elementary:'基礎', Intermediate:'中級', 'Upper Intermediate':'中高級', Advanced:'高級' },
  ja: { Beginner:'初級', Elementary:'初歩', Intermediate:'中級', 'Upper Intermediate':'中上級', Advanced:'上級' },
};

export const scoreUi: Record<UiLanguage, Record<string, string>> = {
  en: {}, 'zh-CN': { coherence:'连贯性', taskResponse:'切题程度', particleUsage:'助词使用', conjugation:'活用', register:'语体与礼貌程度', vocabulary:'词汇', grammar:'语法', naturalness:'自然度', appropriateness:'得体程度' },
  'zh-HK': { coherence:'連貫性', taskResponse:'切題程度', particleUsage:'助詞使用', conjugation:'活用', register:'語體與禮貌程度', vocabulary:'詞彙', grammar:'語法', naturalness:'自然度', appropriateness:'得體程度' },
  ja: { coherence:'一貫性', taskResponse:'課題への応答', particleUsage:'助詞', conjugation:'活用', register:'文体と敬語', vocabulary:'語彙', grammar:'文法', naturalness:'自然さ', appropriateness:'適切さ' },
};
