import type { UiLanguage } from '@/lib/ui-translations';
export const speechUi: Record<UiLanguage, Record<string, string>> = {
  en: { permission: 'Requesting microphone…', analyzing: 'Analyzing audio…', transcribing: 'Transcribing…', evaluating: 'Evaluating answer…', short: 'Recording too short. Speak for at least one second.', empty: 'No audio captured. Try recording again.', retryAnalysis: 'Retry analysis', content: 'Content', delivery: 'Delivery · basic audio estimate', pronunciation: 'Pronunciation', unavailable: 'Pronunciation analysis unavailable. No pronunciation score is shown.', noMetrics: 'Audio analysis unavailable in this browser.', duration: 'Duration', speaking: 'Detected speech', silence: 'Silence', pauses: 'Pauses', longPauses: 'Long pauses', comparison: 'Compared with previous attempt', moreWords: 'Transcript length', pauseChange: 'Long-pause change', sourceNote: 'Estimated from microphone volume; not a pronunciation or fluency score.' },
  'zh-CN': { permission: '正在请求麦克风权限…', analyzing: '正在分析音频…', transcribing: '正在转写…', evaluating: '正在评估回答…', short: '录音太短，请至少说一秒。', empty: '没有录到音频，请重试。', retryAnalysis: '重新分析', content: '内容', delivery: '表达节奏 · 基础音频估计', pronunciation: '发音', unavailable: '尚无发音分析，不显示发音分数。', noMetrics: '此浏览器无法分析音频。', duration: '录音时长', speaking: '检测到的说话时长', silence: '静音', pauses: '停顿', longPauses: '长停顿', comparison: '与上一次尝试比较', moreWords: '转写长度', pauseChange: '长停顿变化', sourceNote: '根据麦克风音量估计；不是发音或流利度评分。' },
  'zh-HK': { permission: '正在要求麥克風權限…', analyzing: '正在分析音訊…', transcribing: '正在轉寫…', evaluating: '正在評估回答…', short: '錄音太短，請至少說一秒。', empty: '沒有錄到音訊，請重試。', retryAnalysis: '重新分析', content: '內容', delivery: '表達節奏 · 基礎音訊估計', pronunciation: '發音', unavailable: '尚無發音分析，不顯示發音分數。', noMetrics: '此瀏覽器無法分析音訊。', duration: '錄音時長', speaking: '偵測到的說話時長', silence: '靜音', pauses: '停頓', longPauses: '長停頓', comparison: '與上一次嘗試比較', moreWords: '轉寫長度', pauseChange: '長停頓變化', sourceNote: '根據麥克風音量估計；並非發音或流暢度評分。' },
  ja: { permission: 'マイクの許可を確認中…', analyzing: '音声を分析中…', transcribing: '文字起こし中…', evaluating: '回答を評価中…', short: '録音が短すぎます。1 秒以上話してください。', empty: '音声が録音されていません。再試行してください。', retryAnalysis: '再分析', content: '内容', delivery: '話し方 · 基本的な音声推定', pronunciation: '発音', unavailable: '発音分析は利用できません。発音スコアは表示しません。', noMetrics: 'このブラウザでは音声分析を利用できません。', duration: '録音時間', speaking: '検出した発話時間', silence: '無音', pauses: '間', longPauses: '長い間', comparison: '前回の試行との比較', moreWords: '文字起こしの長さ', pauseChange: '長い間の変化', sourceNote: 'マイク音量による推定です。発音や流暢さのスコアではありません。' },
};

export const speechErrors: Record<UiLanguage, Record<string, string>> = {
  en: { glmMissing: 'GLM speech key is missing on the server.', glmInvalid: 'GLM key was rejected. Check the key and account access.', glmQuota: 'GLM speech quota or rate limit reached. Try again later or type your answer.', emptyTranscript: 'No speech was recognized. Replay the audio or type your answer.', transcriptionFailed: 'Speech transcription failed. Retry analysis or type your answer.' },
  'zh-CN': { glmMissing: '服务器未配置 GLM 语音密钥。', glmInvalid: 'GLM 密钥被拒绝，请检查密钥与账户权限。', glmQuota: 'GLM 语音额度或请求频率已达上限；稍后重试或手动输入。', emptyTranscript: '没有识别到语音。可回放录音或手动输入。', transcriptionFailed: '转写失败。可重新分析或手动输入。' },
  'zh-HK': { glmMissing: '伺服器未設定 GLM 語音金鑰。', glmInvalid: 'GLM 金鑰遭拒，請檢查金鑰與帳戶權限。', glmQuota: 'GLM 語音額度或請求頻率已達上限；稍後重試或手動輸入。', emptyTranscript: '未識別到語音。可重播錄音或手動輸入。', transcriptionFailed: '轉寫失敗。可重新分析或手動輸入。' },
  ja: { glmMissing: 'サーバーに GLM 音声キーがありません。', glmInvalid: 'GLM キーが拒否されました。キーとアカウント権限を確認してください。', glmQuota: 'GLM 音声の利用枠またはレート制限に達しました。後で再試行するか入力してください。', emptyTranscript: '音声を認識できませんでした。録音を再生するか入力してください。', transcriptionFailed: '文字起こしに失敗しました。再分析するか入力してください。' },
};
