import type { UiLanguage } from '@/lib/ui-translations';
export const speechUi: Record<UiLanguage, Record<string, string>> = {
  en: { permission: 'Requesting microphone…', analyzing: 'Analyzing audio…', transcribing: 'Transcribing…', evaluating: 'Evaluating answer…', short: 'Recording too short. Speak for at least one second.', empty: 'No audio captured. Try recording again.', retryAnalysis: 'Retry analysis', content: 'Content', delivery: 'Delivery · basic audio estimate', pronunciation: 'Pronunciation', unavailable: 'Pronunciation analysis unavailable. No pronunciation score is shown.', noMetrics: 'Audio analysis unavailable in this browser.', duration: 'Duration', seconds: 's', speaking: 'Detected speech', silence: 'Silence', pauses: 'Pauses', longPauses: 'Long pauses', pauseDuration: 'duration', comparison: 'Compared with previous attempt', moreWords: 'Transcript length', pauseChange: 'Long-pause change', sourceNote: 'Estimated from microphone volume; not a pronunciation or fluency score.', combinedBasis: 'Feedback basis: transcript + local basic audio metrics. Original audio was not uploaded to the text model.' },
  'zh-CN': { permission: '正在请求麦克风权限…', analyzing: '正在分析音频…', transcribing: '正在转写…', evaluating: '正在评估回答…', short: '录音太短，请至少说一秒。', empty: '没有录到音频，请重试。', retryAnalysis: '重新分析', content: '内容', delivery: '表达节奏 · 基础音频估计', pronunciation: '发音', unavailable: '尚无发音分析，不显示发音分数。', noMetrics: '此浏览器无法分析音频。', duration: '录音时长', seconds: '秒', speaking: '检测到的说话时长', silence: '静音', pauses: '停顿', longPauses: '长停顿', pauseDuration: '持续', comparison: '与上一次尝试比较', moreWords: '转写长度', pauseChange: '长停顿变化', sourceNote: '根据麦克风音量估计；不是发音或流利度评分。', combinedBasis: '反馈依据：转写文本 + 本地基础音频指标。原始音频未上传给文本模型。' },
  'zh-HK': { permission: '正在要求麥克風權限…', analyzing: '正在分析音訊…', transcribing: '正在轉寫…', evaluating: '正在評估回答…', short: '錄音太短，請至少說一秒。', empty: '沒有錄到音訊，請重試。', retryAnalysis: '重新分析', content: '內容', delivery: '表達節奏 · 基礎音訊估計', pronunciation: '發音', unavailable: '尚無發音分析，不顯示發音分數。', noMetrics: '此瀏覽器無法分析音訊。', duration: '錄音時長', seconds: '秒', speaking: '偵測到的說話時長', silence: '靜音', pauses: '停頓', longPauses: '長停頓', pauseDuration: '持續', comparison: '與上一次嘗試比較', moreWords: '轉寫長度', pauseChange: '長停頓變化', sourceNote: '根據麥克風音量估計；並非發音或流暢度評分。', combinedBasis: '回饋依據：轉寫文字 + 本機基礎音訊指標。原始音訊未上傳至文字模型。' },
  ja: { permission: 'マイクの許可を確認中…', analyzing: '音声を分析中…', transcribing: '文字起こし中…', evaluating: '回答を評価中…', short: '録音が短すぎます。1 秒以上話してください。', empty: '音声が録音されていません。再試行してください。', retryAnalysis: '再分析', content: '内容', delivery: '話し方 · 基本的な音声推定', pronunciation: '発音', unavailable: '発音分析は利用できません。発音スコアは表示しません。', noMetrics: 'このブラウザでは音声分析を利用できません。', duration: '録音時間', seconds: '秒', speaking: '検出した発話時間', silence: '無音', pauses: '間', longPauses: '長い間', pauseDuration: '継続', comparison: '前回の試行との比較', moreWords: '文字起こしの長さ', pauseChange: '長い間の変化', sourceNote: 'マイク音量による推定です。発音や流暢さのスコアではありません。', combinedBasis: '評価根拠：文字起こし + 端末内の基本音声指標。元音声はテキストモデルへ送信していません。' },
};

export const speechErrors: Record<UiLanguage, Record<string, string>> = {
  en: { glmMissing: 'GLM speech key is missing on the server.', glmInvalid: 'GLM key was rejected. Check the key and account access.', glmQuota: 'GLM speech quota or rate limit reached. Try again later or type your answer.', betaDailyLimit: 'This account’s daily transcription limit is reached. Each recording counts once. Try after the UTC daily reset or type your answer.', betaAccessDenied: 'Test access code was rejected. Check it in Interface settings.', betaUnavailable: 'Test access control is unavailable on the server.', partialTranscript: 'The recognized part is kept below; the remaining audio was not transcribed.', emptyTranscript: 'No speech was recognized. Replay the audio or type your answer.', transcriptionFailed: 'Speech transcription failed. Retry analysis or type your answer.' },
  'zh-CN': { glmMissing: '服务器未配置 GLM 语音密钥。', glmInvalid: 'GLM 密钥被拒绝，请检查密钥与账户权限。', glmQuota: 'GLM 语音额度或请求频率已达上限；稍后重试或手动输入。', betaDailyLimit: '此账号今日转写额度已用尽。每段录音只计一次；请在 UTC 日期重置后再试，或手动输入。', betaAccessDenied: '测试访问码被拒绝，请在界面设置中检查。', betaUnavailable: '服务器的测试访问控制暂不可用。', partialTranscript: '已保留下方识别成功的部分；后续音频未能转写。', emptyTranscript: '没有识别到语音。可回放录音或手动输入。', transcriptionFailed: '转写失败。可重新分析或手动输入。' },
  'zh-HK': { glmMissing: '伺服器未設定 GLM 語音金鑰。', glmInvalid: 'GLM 金鑰遭拒，請檢查金鑰與帳戶權限。', glmQuota: 'GLM 語音額度或請求頻率已達上限；稍後重試或手動輸入。', betaDailyLimit: '此帳戶今日轉寫額度已用盡。每段錄音只計一次；請在 UTC 日期重設後再試，或手動輸入。', betaAccessDenied: '測試存取碼遭拒，請在介面設定中檢查。', betaUnavailable: '伺服器的測試存取控制暫時無法使用。', partialTranscript: '下方已保留成功辨識的部分；後續音訊未能轉寫。', emptyTranscript: '未識別到語音。可重播錄音或手動輸入。', transcriptionFailed: '轉寫失敗。可重新分析或手動輸入。' },
  ja: { glmMissing: 'サーバーに GLM 音声キーがありません。', glmInvalid: 'GLM キーが拒否されました。キーとアカウント権限を確認してください。', glmQuota: 'GLM 音声の利用枠またはレート制限に達しました。後で再試行するか入力してください。', betaDailyLimit: 'このアカウントの本日の文字起こし上限に達しました。録音 1 件につき 1 回のみ計上されます。UTC 日付のリセット後に再試行するか、手入力してください。', betaAccessDenied: 'テストアクセスコードが拒否されました。表示設定で確認してください。', betaUnavailable: 'サーバーのテストアクセス制御を利用できません。', partialTranscript: '認識できた部分は下に残しました。残りの音声は文字起こしできませんでした。', emptyTranscript: '音声を認識できませんでした。録音を再生するか入力してください。', transcriptionFailed: '文字起こしに失敗しました。再分析するか入力してください。' },
};
